/* Generated by re2c 0.12.2 */
//////////////////////////////////////////////////////////////////////////
//
// This file is © 2007 - 2009 JJ Fahner <jan-jaap@jan-jaap.net>
// This file is part of the cscript interpreter.
// CScript can be found at http://svn.jan-jaap.net/
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//////////////////////////////////////////////////////////////////////////

int parseNextToken(Char*& start, Char*& end)
{
  Char* qptr = 0;
  
  if(*start == 0)
  {
    return 0;
  }
  
  	{
		static const unsigned char yybm[] = {
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  17,  16,  16,  16,  18,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 17,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			124, 124,  60,  60,  60,  60,  60,  60, 
			 60,  60,  16,  16,  16,  16,  16,  16, 
			 16,  52,  52, 180, 180,  52,  52,  20, 
			 20, 148,  20,  20, 148, 148,  20, 148, 
			 20,  20,  20,  20,  20,  20, 148,  20, 
			148,  20,  20,  16,  16,  16,  16,  20, 
			  0,  52,  52,  52,  52,  52,  52,  20, 
			 20,  20,  20,  20,  20,  20,  20,  20, 
			 20,  20,  20,  20,  20,  20,  20,  20, 
			 20,  20,  20,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
		};

		{
			Char yych;
			unsigned int yyaccept = 0;

			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 1) {
				goto yy3;
			}
			switch(yych) {
			case 0x000A:	goto yy8;
			case 0x000D:	goto yy6;
			case '!':	goto yy40;
			case '"':	goto yy33;
			case '%':	goto yy52;
			case '&':	goto yy56;
			case '(':	goto yy72;
			case ')':	goto yy74;
			case '*':	goto yy50;
			case '+':	goto yy46;
			case ',':	goto yy64;
			case '-':	goto yy48;
			case '.':	goto yy36;
			case '/':	goto yy10;
			case '0':	goto yy29;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy31;
			case ':':	goto yy60;
			case ';':	goto yy62;
			case '<':	goto yy42;
			case '=':	goto yy38;
			case '>':	goto yy44;
			case '?':	goto yy58;
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'g':
			case 'h':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'p':
			case 'q':
			case 'u':
			case 'x':
			case 'y':
			case 'z':	goto yy27;
			case '[':	goto yy68;
			case ']':	goto yy70;
			case '^':	goto yy66;
			case '_':	goto yy12;
			case '`':	goto yy35;
			case 'b':	goto yy14;
			case 'c':	goto yy15;
			case 'd':	goto yy16;
			case 'e':	goto yy17;
			case 'f':	goto yy18;
			case 'i':	goto yy19;
			case 'n':	goto yy20;
			case 'o':	goto yy21;
			case 'r':	goto yy22;
			case 's':	goto yy23;
			case 't':	goto yy24;
			case 'v':	goto yy25;
			case 'w':	goto yy26;
			case '{':	goto yy76;
			case '|':	goto yy54;
			case '}':	goto yy78;
			default:	goto yy2;
			}
yy2:
			end = qptr;
			if(yyaccept <= 0) {
				goto yy30;
			} else {
				goto yy37;
			}
yy3:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 1) {
				goto yy3;
			}
			{ return TOK_WHITESPACE; }
yy6:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
				goto yy2;
			} else if(yybm[0+yych] & 2) {
				goto yy6;
			}
			if(yych != 0x000A) goto yy2;
yy8:
			++end;
			{ return TOK_NEWLINE; }
yy10:
			++end;
			if((yych = (Char)*end) <= '.') {
				if(yych == '*') goto yy288;
			} else {
				if(yych <= '/') goto yy290;
				if(yych == '=') goto yy286;
			}
			{ return TOK_DIVOP; }
yy12:
			++end;
			if((yych = (Char)*end) == '_') goto yy278;
			goto yy28;
yy13:
			{ return TOK_IDENTIFIER; }
yy14:
			yych = (Char)*++end;
			if(yych == 'o') goto yy269;
			if(yych == 'r') goto yy270;
			goto yy28;
yy15:
			yych = (Char)*++end;
			if(yych == 'a') goto yy253;
			if(yych == 'o') goto yy254;
			goto yy28;
yy16:
			yych = (Char)*++end;
			if(yych == 'e') goto yy246;
			goto yy28;
yy17:
			yych = (Char)*++end;
			if(yych == 'l') goto yy236;
			if(yych == 'x') goto yy237;
			goto yy28;
yy18:
			yych = (Char)*++end;
			if(yych <= 'i') {
				if(yych == 'a') goto yy213;
				if(yych <= 'h') goto yy28;
				goto yy214;
			} else {
				if(yych <= 'o') {
					if(yych <= 'n') goto yy28;
					goto yy215;
				} else {
					if(yych == 'u') goto yy216;
					goto yy28;
				}
			}
yy19:
			yych = (Char)*++end;
			if(yych == 'f') goto yy201;
			if(yych == 'n') goto yy203;
			goto yy28;
yy20:
			yych = (Char)*++end;
			if(yych <= 'd') {
				if(yych == 'a') goto yy185;
				goto yy28;
			} else {
				if(yych <= 'e') goto yy186;
				if(yych == 'u') goto yy187;
				goto yy28;
			}
yy21:
			yych = (Char)*++end;
			if(yych == 'p') goto yy177;
			goto yy28;
yy22:
			yych = (Char)*++end;
			if(yych == 'e') goto yy171;
			goto yy28;
yy23:
			yych = (Char)*++end;
			if(yych == 't') goto yy159;
			if(yych == 'w') goto yy160;
			goto yy28;
yy24:
			yych = (Char)*++end;
			if(yych == 'h') goto yy145;
			if(yych == 'r') goto yy146;
			goto yy28;
yy25:
			yych = (Char)*++end;
			if(yych == 'a') goto yy142;
			goto yy28;
yy26:
			yych = (Char)*++end;
			if(yych == 'h') goto yy137;
			goto yy28;
yy27:
			++end;
			yych = (Char)*end;
yy28:
			if(yych & ~0xFF) {
				goto yy13;
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			goto yy13;
yy29:
			yyaccept = 0;
			yych = (Char)*(qptr = ++end);
			if(yych <= 'q') {
				if(yych == 'b') goto yy126;
				goto yy32;
			} else {
				if(yych <= 'r') goto yy125;
				if(yych == 'x') goto yy127;
				goto yy32;
			}
yy30:
			{ return TOK_LIT_INTEGER; }
yy31:
			yyaccept = 0;
			qptr = ++end;
			yych = (Char)*end;
yy32:
			if(yych & ~0xFF) {
				goto yy30;
			} else if(yybm[0+yych] & 8) {
				goto yy31;
			}
			if(yych == '.') goto yy121;
			goto yy30;
yy33:
			++end;
			{ return TOK_LIT_STRING; }
yy35:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
				goto yy117;
			} else if(yybm[0+yych] & 16) {
				goto yy117;
			}
			goto yy2;
yy36:
			yyaccept = 1;
			yych = (Char)*(qptr = ++end);
			if(yych == '.') goto yy114;
yy37:
			{ return TOK_DOT; }
yy38:
			++end;
			if((yych = (Char)*end) == '=') goto yy110;
			{ return TOK_ASSIGN; }
yy40:
			++end;
			if((yych = (Char)*end) == '=') goto yy106;
			{ return TOK_NOT; }
yy42:
			++end;
			if((yych = (Char)*end) == '=') goto yy104;
			if(yych == '?') goto yy102;
			{ return TOK_LT; }
yy44:
			++end;
			if((yych = (Char)*end) == '=') goto yy100;
			{ return TOK_GT; }
yy46:
			++end;
			if((yych = (Char)*end) == '+') goto yy98;
			if(yych == '=') goto yy96;
			{ return TOK_ADDOP; }
yy48:
			++end;
			if((yych = (Char)*end) == '-') goto yy94;
			if(yych == '=') goto yy92;
			{ return TOK_SUBOP; }
yy50:
			++end;
			if((yych = (Char)*end) == '=') goto yy90;
			{ return TOK_MULOP; }
yy52:
			++end;
			if((yych = (Char)*end) == '=') goto yy88;
			{ return TOK_MODOP; }
yy54:
			++end;
			if((yych = (Char)*end) == '|') goto yy86;
			{ return TOK_BITOR; }
yy56:
			++end;
			if((yych = (Char)*end) == '&') goto yy84;
			{ return TOK_BITAND; }
yy58:
			++end;
			if((yych = (Char)*end) == '>') goto yy82;
			{ return TOK_QUESTION; }
yy60:
			++end;
			if((yych = (Char)*end) == ':') goto yy80;
			{ return TOK_COLON; }
yy62:
			++end;
			{ return TOK_SEMICOLON; }
yy64:
			++end;
			{ return TOK_COMMA; }
yy66:
			++end;
			{ return TOK_BITXOR; }
yy68:
			++end;
			{ return TOK_LBRACKET; }
yy70:
			++end;
			{ return TOK_RBRACKET; }
yy72:
			++end;
			{ return TOK_LPAREN; }
yy74:
			++end;
			{ return TOK_RPAREN; }
yy76:
			++end;
			{ return TOK_LBRACE; }
yy78:
			++end;
			{ return TOK_RBRACE; }
yy80:
			++end;
			{ return TOK_NS_SEP; }
yy82:
			++end;
			{ return TOK_XMLPRC; }
yy84:
			++end;
			{ return TOK_LOGAND; }
yy86:
			++end;
			{ return TOK_LOGOR; }
yy88:
			++end;
			{ return TOK_ASSMOD; }
yy90:
			++end;
			{ return TOK_ASSMUL; }
yy92:
			++end;
			{ return TOK_ASSSUB; }
yy94:
			++end;
			{ return TOK_SUBSUB; }
yy96:
			++end;
			{ return TOK_ASSADD; }
yy98:
			++end;
			{ return TOK_ADDADD; }
yy100:
			++end;
			{ return TOK_GE; }
yy102:
			++end;
			{ return TOK_XMLPRO; }
yy104:
			++end;
			{ return TOK_LE; }
yy106:
			++end;
			if((yych = (Char)*end) == '=') goto yy108;
			{ return TOK_NEQUALS; }
yy108:
			++end;
			{ return TOK_SNE; }
yy110:
			++end;
			if((yych = (Char)*end) == '=') goto yy112;
			{ return TOK_EQUALS; }
yy112:
			++end;
			{ return TOK_SEQ; }
yy114:
			yych = (Char)*++end;
			if(yych != '.') goto yy2;
			++end;
			{ return TOK_VARIADIC; }
yy117:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 16) {
				goto yy117;
			}
			++end;
			{ return TOK_SHELLCMD; }
yy121:
			yych = (Char)*++end;
			if(yych <= '/') goto yy2;
			if(yych >= ':') goto yy2;
yy122:
			++end;
			yych = (Char)*end;
			if(yych <= '/') goto yy124;
			if(yych <= '9') goto yy122;
yy124:
			{ return TOK_LIT_REAL; }
yy125:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
				goto yy2;
			} else if(yybm[0+yych] & 128) {
				goto yy134;
			}
			goto yy2;
yy126:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
				goto yy2;
			} else if(yybm[0+yych] & 64) {
				goto yy131;
			}
			goto yy2;
yy127:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 32) {
				goto yy128;
			}
			goto yy2;
yy128:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 32) {
				goto yy128;
			}
			{ return TOK_LIT_HEX; }
yy131:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 64) {
				goto yy131;
			}
			{ return TOK_LIT_BIN; }
yy134:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 128) {
				goto yy134;
			}
			{ return TOK_LIT_ROM; }
yy137:
			yych = (Char)*++end;
			if(yych != 'i') goto yy28;
			yych = (Char)*++end;
			if(yych != 'l') goto yy28;
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_WHILE; }
yy142:
			yych = (Char)*++end;
			if(yych != 'r') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_VAR; }
yy145:
			yych = (Char)*++end;
			if(yych == 'i') goto yy152;
			if(yych == 'r') goto yy153;
			goto yy28;
yy146:
			yych = (Char)*++end;
			if(yych == 'u') goto yy147;
			if(yych == 'y') goto yy148;
			goto yy28;
yy147:
			yych = (Char)*++end;
			if(yych == 'e') goto yy150;
			goto yy28;
yy148:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_TRY; }
yy150:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_TRUE; }
yy152:
			yych = (Char)*++end;
			if(yych == 's') goto yy157;
			goto yy28;
yy153:
			yych = (Char)*++end;
			if(yych != 'o') goto yy28;
			yych = (Char)*++end;
			if(yych != 'w') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_THROW; }
yy157:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_THIS; }
yy159:
			yych = (Char)*++end;
			if(yych == 'r') goto yy166;
			goto yy28;
yy160:
			yych = (Char)*++end;
			if(yych != 'i') goto yy28;
			yych = (Char)*++end;
			if(yych != 't') goto yy28;
			yych = (Char)*++end;
			if(yych != 'c') goto yy28;
			yych = (Char)*++end;
			if(yych != 'h') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_SWITCH; }
yy166:
			yych = (Char)*++end;
			if(yych != 'i') goto yy28;
			yych = (Char)*++end;
			if(yych != 'n') goto yy28;
			yych = (Char)*++end;
			if(yych != 'g') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_STRING; }
yy171:
			yych = (Char)*++end;
			if(yych != 't') goto yy28;
			yych = (Char)*++end;
			if(yych != 'u') goto yy28;
			yych = (Char)*++end;
			if(yych != 'r') goto yy28;
			yych = (Char)*++end;
			if(yych != 'n') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_RETURN; }
yy177:
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			yych = (Char)*++end;
			if(yych != 'r') goto yy28;
			yych = (Char)*++end;
			if(yych != 'a') goto yy28;
			yych = (Char)*++end;
			if(yych != 't') goto yy28;
			yych = (Char)*++end;
			if(yych != 'o') goto yy28;
			yych = (Char)*++end;
			if(yych != 'r') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_OPERATOR; }
yy185:
			yych = (Char)*++end;
			if(yych == 'm') goto yy193;
			goto yy28;
yy186:
			yych = (Char)*++end;
			if(yych == 'w') goto yy191;
			goto yy28;
yy187:
			yych = (Char)*++end;
			if(yych != 'l') goto yy28;
			yych = (Char)*++end;
			if(yych != 'l') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_NULL; }
yy191:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_NEW; }
yy193:
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			yych = (Char)*++end;
			if(yych != 's') goto yy28;
			yych = (Char)*++end;
			if(yych != 'p') goto yy28;
			yych = (Char)*++end;
			if(yych != 'a') goto yy28;
			yych = (Char)*++end;
			if(yych != 'c') goto yy28;
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_NAMESPACE; }
yy201:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_IF; }
yy203:
			++end;
			if((yych = (Char)*end) <= '_') {
				if(yych <= '@') {
					if(yych <= '/') goto yy204;
					if(yych <= '9') goto yy27;
				} else {
					if(yych <= 'Z') goto yy27;
					if(yych >= '_') goto yy27;
				}
			} else {
				if(yych <= 'c') {
					if(yych <= '`') goto yy204;
					if(yych <= 'b') goto yy27;
					goto yy205;
				} else {
					if(yych == 't') goto yy206;
					if(yych <= 'z') goto yy27;
				}
			}
yy204:
			{ return TOK_IN; }
yy205:
			yych = (Char)*++end;
			if(yych == 'l') goto yy208;
			goto yy28;
yy206:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_INT; }
yy208:
			yych = (Char)*++end;
			if(yych != 'u') goto yy28;
			yych = (Char)*++end;
			if(yych != 'd') goto yy28;
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_INCLUDE; }
yy213:
			yych = (Char)*++end;
			if(yych == 'l') goto yy232;
			goto yy28;
yy214:
			yych = (Char)*++end;
			if(yych == 'n') goto yy226;
			goto yy28;
yy215:
			yych = (Char)*++end;
			if(yych == 'r') goto yy224;
			goto yy28;
yy216:
			yych = (Char)*++end;
			if(yych != 'n') goto yy28;
			yych = (Char)*++end;
			if(yych != 'c') goto yy28;
			yych = (Char)*++end;
			if(yych != 't') goto yy28;
			yych = (Char)*++end;
			if(yych != 'i') goto yy28;
			yych = (Char)*++end;
			if(yych != 'o') goto yy28;
			yych = (Char)*++end;
			if(yych != 'n') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_FUNCTION; }
yy224:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_FOR; }
yy226:
			yych = (Char)*++end;
			if(yych != 'a') goto yy28;
			yych = (Char)*++end;
			if(yych != 'l') goto yy28;
			yych = (Char)*++end;
			if(yych != 'l') goto yy28;
			yych = (Char)*++end;
			if(yych != 'y') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_FINALLY; }
yy232:
			yych = (Char)*++end;
			if(yych != 's') goto yy28;
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_FALSE; }
yy236:
			yych = (Char)*++end;
			if(yych == 's') goto yy243;
			goto yy28;
yy237:
			yych = (Char)*++end;
			if(yych != 't') goto yy28;
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			yych = (Char)*++end;
			if(yych != 'r') goto yy28;
			yych = (Char)*++end;
			if(yych != 'n') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_EXTERN; }
yy243:
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_ELSE; }
yy246:
			yych = (Char)*++end;
			if(yych != 'f') goto yy28;
			yych = (Char)*++end;
			if(yych != 'a') goto yy28;
			yych = (Char)*++end;
			if(yych != 'u') goto yy28;
			yych = (Char)*++end;
			if(yych != 'l') goto yy28;
			yych = (Char)*++end;
			if(yych != 't') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_DEFAULT; }
yy253:
			yych = (Char)*++end;
			if(yych <= 'r') goto yy28;
			if(yych <= 's') goto yy262;
			if(yych <= 't') goto yy263;
			goto yy28;
yy254:
			yych = (Char)*++end;
			if(yych != 'n') goto yy28;
			yych = (Char)*++end;
			if(yych != 't') goto yy28;
			yych = (Char)*++end;
			if(yych != 'i') goto yy28;
			yych = (Char)*++end;
			if(yych != 'n') goto yy28;
			yych = (Char)*++end;
			if(yych != 'u') goto yy28;
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_CONTINUE; }
yy262:
			yych = (Char)*++end;
			if(yych == 'e') goto yy267;
			goto yy28;
yy263:
			yych = (Char)*++end;
			if(yych != 'c') goto yy28;
			yych = (Char)*++end;
			if(yych != 'h') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_CATCH; }
yy267:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_CASE; }
yy269:
			yych = (Char)*++end;
			if(yych == 'o') goto yy275;
			goto yy28;
yy270:
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			yych = (Char)*++end;
			if(yych != 'a') goto yy28;
			yych = (Char)*++end;
			if(yych != 'k') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_BREAK; }
yy275:
			yych = (Char)*++end;
			if(yych != 'l') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_BOOL; }
yy278:
			yych = (Char)*++end;
			if(yych != 'n') goto yy28;
			yych = (Char)*++end;
			if(yych != 'a') goto yy28;
			yych = (Char)*++end;
			if(yych != 't') goto yy28;
			yych = (Char)*++end;
			if(yych != 'i') goto yy28;
			yych = (Char)*++end;
			if(yych != 'v') goto yy28;
			yych = (Char)*++end;
			if(yych != 'e') goto yy28;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy27;
			}
			{ return TOK_NATIVE; }
yy286:
			++end;
			{ return TOK_ASSDIV; }
yy288:
			++end;
			{ return TOK_COMMENT; }
yy290:
			++end;
			{ return TOK_COMMENT; }
		}
	}

}
