#define TOK_LOGOR                           1
#define TOK_LOGAND                          2
#define TOK_BITOR                           3
#define TOK_BITXOR                          4
#define TOK_BITAND                          5
#define TOK_EQUALS                          6
#define TOK_NEQUALS                         7
#define TOK_ST                              8
#define TOK_SE                              9
#define TOK_GT                             10
#define TOK_GE                             11
#define TOK_ADDOP                          12
#define TOK_SUBOP                          13
#define TOK_MULOP                          14
#define TOK_DIVOP                          15
#define TOK_MODOP                          16
#define TOK_ASSIGN                         17
#define TOK_ASSADD                         18
#define TOK_ASSSUB                         19
#define TOK_ASSMUL                         20
#define TOK_ASSDIV                         21
#define TOK_ASSMOD                         22
#define TOK_QUESTION                       23
#define TOK_COLON                          24
#define TOK_ADDADD                         25
#define TOK_SUBSUB                         26
#define TOK_DOT                            27
#define TOK_LBRACKET                       28
#define TOK_RBRACKET                       29
#define TOK_IDENTIFIER                     30
#define TOK_LPAREN                         31
#define TOK_RPAREN                         32
#define TOK_INTEGER                        33
#define TOK_REAL                           34
#define TOK_STRING                         35
#define TOK_TRUE                           36
#define TOK_FALSE                          37
#define TOK_NULL                           38
#define TOK_COMMA                          39
#define TOK_SEMICOLON                      40
#define TOK_LBRACE                         41
#define TOK_RBRACE                         42
#define TOK_INCLUDE                        43
#define TOK_RETURN                         44
#define TOK_VAR                            45
#define TOK_FUNCTION                       46
#define TOK_FOR                            47
#define TOK_IN                             48
#define TOK_LOWER_THAN_ELSE                49
#define TOK_ELSE                           50
#define TOK_IF                             51
#define TOK_WHILE                          52
