#define TOK_LOGOR                           1
#define TOK_LOGAND                          2
#define TOK_BITOR                           3
#define TOK_BITXOR                          4
#define TOK_BITAND                          5
#define TOK_SEQ                             6
#define TOK_SNE                             7
#define TOK_EQUALS                          8
#define TOK_NEQUALS                         9
#define TOK_ST                             10
#define TOK_SE                             11
#define TOK_GT                             12
#define TOK_GE                             13
#define TOK_ADDOP                          14
#define TOK_SUBOP                          15
#define TOK_MULOP                          16
#define TOK_DIVOP                          17
#define TOK_MODOP                          18
#define TOK_ASSIGN                         19
#define TOK_ASSADD                         20
#define TOK_ASSSUB                         21
#define TOK_ASSMUL                         22
#define TOK_ASSDIV                         23
#define TOK_ASSMOD                         24
#define TOK_QUESTION                       25
#define TOK_COLON                          26
#define TOK_ADDADD                         27
#define TOK_SUBSUB                         28
#define TOK_NOT                            29
#define TOK_DOT                            30
#define TOK_IDENTIFIER                     31
#define TOK_LBRACKET                       32
#define TOK_RBRACKET                       33
#define TOK_LPAREN                         34
#define TOK_RPAREN                         35
#define TOK_THIS                           36
#define TOK_INTEGER                        37
#define TOK_HEX                            38
#define TOK_BIN                            39
#define TOK_ROM                            40
#define TOK_REAL                           41
#define TOK_STRING                         42
#define TOK_TRUE                           43
#define TOK_FALSE                          44
#define TOK_NULL                           45
#define TOK_COMMA                          46
#define TOK_NEW                            47
#define TOK_SEMICOLON                      48
#define TOK_LBRACE                         49
#define TOK_RBRACE                         50
#define TOK_INCLUDE                        51
#define TOK_RETURN                         52
#define TOK_BREAK                          53
#define TOK_CONTINUE                       54
#define TOK_VAR                            55
#define TOK_CLASS                          56
#define TOK_PRIVATE                        57
#define TOK_PROTECTED                      58
#define TOK_PUBLIC                         59
#define TOK_FUNCTION                       60
#define TOK_FOR                            61
#define TOK_IN                             62
#define TOK_LOWER_THAN_ELSE                63
#define TOK_ELSE                           64
#define TOK_IF                             65
#define TOK_WHILE                          66
#define TOK_SWITCH                         67
#define TOK_CASE                           68
#define TOK_DEFAULT                        69
#define TOK_EXTERN                         70
#define TOK_INT                            71
#define TOK_STR                            72
