#define TOK_LOGOR                           1
#define TOK_LOGAND                          2
#define TOK_BITOR                           3
#define TOK_BITXOR                          4
#define TOK_BITAND                          5
#define TOK_SEQ                             6
#define TOK_SNE                             7
#define TOK_EQUALS                          8
#define TOK_NEQUALS                         9
#define TOK_LT                             10
#define TOK_LE                             11
#define TOK_GT                             12
#define TOK_GE                             13
#define TOK_ADDOP                          14
#define TOK_SUBOP                          15
#define TOK_MULOP                          16
#define TOK_DIVOP                          17
#define TOK_MODOP                          18
#define TOK_ASSIGN                         19
#define TOK_ASSADD                         20
#define TOK_ASSSUB                         21
#define TOK_ASSMUL                         22
#define TOK_ASSDIV                         23
#define TOK_ASSMOD                         24
#define TOK_ADDADD                         25
#define TOK_SUBSUB                         26
#define TOK_NOT                            27
#define TOK_LPAREN                         28
#define TOK_RPAREN                         29
#define TOK_DOT                            30
#define TOK_LBRACKET                       31
#define TOK_RBRACKET                       32
#define TOK_FUNCTION                       33
#define TOK_THIS                           34
#define TOK_LIT_INTEGER                    35
#define TOK_LIT_HEX                        36
#define TOK_LIT_BIN                        37
#define TOK_LIT_ROM                        38
#define TOK_LIT_REAL                       39
#define TOK_LIT_STRING                     40
#define TOK_TRUE                           41
#define TOK_FALSE                          42
#define TOK_NULL                           43
#define TOK_IDENTIFIER                     44
#define TOK_NS_SEP                         45
#define TOK_COMMA                          46
#define TOK_COLON                          47
#define TOK_LBRACE                         48
#define TOK_RBRACE                         49
#define TOK_NEW                            50
#define TOK_SHELLCMD                       51
#define TOK_BOOL                           52
#define TOK_INT                            53
#define TOK_STRING                         54
#define TOK_TYPE                           55
#define TOK_SEMICOLON                      56
#define TOK_INCLUDE                        57
#define TOK_RETURN                         58
#define TOK_BREAK                          59
#define TOK_CONTINUE                       60
#define TOK_VAR                            61
#define TOK_NAMESPACE                      62
#define TOK_NATIVE                         63
#define TOK_VARIADIC                       64
#define TOK_OPERATOR                       65
#define TOK_EXTERN                         66
#define TOK_FOR                            67
#define TOK_IN                             68
#define TOK_LOWER_THAN_ELSE                69
#define TOK_ELSE                           70
#define TOK_IF                             71
#define TOK_WHILE                          72
#define TOK_SWITCH                         73
#define TOK_CASE                           74
#define TOK_DEFAULT                        75
#define TOK_TRY                            76
#define TOK_CATCH                          77
#define TOK_FINALLY                        78
#define TOK_THROW                          79
#define TOK_XMLPRO                         80
#define TOK_XMLPRC                         81
#define TOK_XMLTEXT                        82
