#define TOK_COMMENT                         1
#define TOK_NEWLINE                         2
#define TOK_WHITESPACE                      3
#define TOK_ASSIGN                          4
#define TOK_ASSADD                          5
#define TOK_ASSSUB                          6
#define TOK_ASSMUL                          7
#define TOK_ASSDIV                          8
#define TOK_ASSMOD                          9
#define TOK_QUESTION                       10
#define TOK_LOGOR                          11
#define TOK_LOGAND                         12
#define TOK_BITOR                          13
#define TOK_BITXOR                         14
#define TOK_BITAND                         15
#define TOK_SEQ                            16
#define TOK_SNE                            17
#define TOK_EQUALS                         18
#define TOK_NEQUALS                        19
#define TOK_LT                             20
#define TOK_LE                             21
#define TOK_GT                             22
#define TOK_GE                             23
#define TOK_ADDOP                          24
#define TOK_SUBOP                          25
#define TOK_MULOP                          26
#define TOK_DIVOP                          27
#define TOK_MODOP                          28
#define TOK_COLON                          29
#define TOK_ADDADD                         30
#define TOK_SUBSUB                         31
#define TOK_NOT                            32
#define TOK_LPAREN                         33
#define TOK_RPAREN                         34
#define TOK_DOT                            35
#define TOK_LBRACKET                       36
#define TOK_RBRACKET                       37
#define TOK_FUNCTION                       38
#define TOK_THIS                           39
#define TOK_LIT_INTEGER                    40
#define TOK_LIT_HEX                        41
#define TOK_LIT_BIN                        42
#define TOK_LIT_ROM                        43
#define TOK_LIT_REAL                       44
#define TOK_LIT_STRING                     45
#define TOK_TRUE                           46
#define TOK_FALSE                          47
#define TOK_NULL                           48
#define TOK_IDENTIFIER                     49
#define TOK_NS_SEP                         50
#define TOK_COMMA                          51
#define TOK_LBRACE                         52
#define TOK_RBRACE                         53
#define TOK_NEW                            54
#define TOK_SHELLCMD                       55
#define TOK_BOOL                           56
#define TOK_INT                            57
#define TOK_STRING                         58
#define TOK_TYPE                           59
#define TOK_SEMICOLON                      60
#define TOK_INCLUDE                        61
#define TOK_RETURN                         62
#define TOK_BREAK                          63
#define TOK_CONTINUE                       64
#define TOK_VAR                            65
#define TOK_NAMESPACE                      66
#define TOK_UNSET                          67
#define TOK_NATIVE                         68
#define TOK_VARIADIC                       69
#define TOK_OPERATOR                       70
#define TOK_EXTERN                         71
#define TOK_FOR                            72
#define TOK_IN                             73
#define TOK_LOWER_THAN_ELSE                74
#define TOK_ELSE                           75
#define TOK_IF                             76
#define TOK_WHILE                          77
#define TOK_SWITCH                         78
#define TOK_CASE                           79
#define TOK_DEFAULT                        80
#define TOK_TRY                            81
#define TOK_CATCH                          82
#define TOK_FINALLY                        83
#define TOK_THROW                          84
#define TOK_XMLPRO                         85
#define TOK_XMLPRC                         86
#define TOK_XMLTEXT                        87
