/* Generated by re2c 0.12.2 */
//////////////////////////////////////////////////////////////////////////
//
// This file is © 2007 - 2009 JJ Fahner <jan-jaap@jan-jaap.net>
// This file is part of the cscript interpreter.
// CScript can be found at http://svn.jan-jaap.net/
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//////////////////////////////////////////////////////////////////////////

int parseNextToken(Char*& start, Char*& end)
{
  Char* qptr = 0;
  
  if(*start == 0)
  {
    return 0;
  }
  
  	{
		static const unsigned char yybm[] = {
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  17,  16,  16,  16,  18,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 17,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			124, 124,  60,  60,  60,  60,  60,  60, 
			 60,  60,  16,  16,  16,  16,  16,  16, 
			 16,  52,  52, 180, 180,  52,  52,  20, 
			 20, 148,  20,  20, 148, 148,  20, 148, 
			 20,  20,  20,  20,  20,  20, 148,  20, 
			148,  20,  20,  16,  16,  16,  16,  20, 
			  0,  52,  52,  52,  52,  52,  52,  20, 
			 20,  20,  20,  20,  20,  20,  20,  20, 
			 20,  20,  20,  20,  20,  20,  20,  20, 
			 20,  20,  20,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
		};

		{
			Char yych;
			unsigned int yyaccept = 0;

			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 1) {
				goto yy3;
			}
			switch(yych) {
			case 0x000A:	goto yy8;
			case 0x000D:	goto yy6;
			case '!':	goto yy41;
			case '"':	goto yy34;
			case '%':	goto yy53;
			case '&':	goto yy57;
			case '(':	goto yy73;
			case ')':	goto yy75;
			case '*':	goto yy51;
			case '+':	goto yy47;
			case ',':	goto yy65;
			case '-':	goto yy49;
			case '.':	goto yy37;
			case '/':	goto yy10;
			case '0':	goto yy30;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy32;
			case ':':	goto yy61;
			case ';':	goto yy63;
			case '<':	goto yy43;
			case '=':	goto yy39;
			case '>':	goto yy45;
			case '?':	goto yy59;
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'g':
			case 'h':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'p':
			case 'q':
			case 'x':
			case 'y':
			case 'z':	goto yy28;
			case '[':	goto yy69;
			case ']':	goto yy71;
			case '^':	goto yy67;
			case '_':	goto yy12;
			case '`':	goto yy36;
			case 'b':	goto yy14;
			case 'c':	goto yy15;
			case 'd':	goto yy16;
			case 'e':	goto yy17;
			case 'f':	goto yy18;
			case 'i':	goto yy19;
			case 'n':	goto yy20;
			case 'o':	goto yy21;
			case 'r':	goto yy22;
			case 's':	goto yy23;
			case 't':	goto yy24;
			case 'u':	goto yy25;
			case 'v':	goto yy26;
			case 'w':	goto yy27;
			case '{':	goto yy77;
			case '|':	goto yy55;
			case '}':	goto yy79;
			default:	goto yy2;
			}
yy2:
			end = qptr;
			if(yyaccept <= 0) {
				goto yy31;
			} else {
				goto yy38;
			}
yy3:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 1) {
				goto yy3;
			}
			{ return TOK_WHITESPACE; }
yy6:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
				goto yy2;
			} else if(yybm[0+yych] & 2) {
				goto yy6;
			}
			if(yych != 0x000A) goto yy2;
yy8:
			++end;
			{ return TOK_NEWLINE; }
yy10:
			++end;
			if((yych = (Char)*end) <= '.') {
				if(yych == '*') goto yy294;
			} else {
				if(yych <= '/') goto yy296;
				if(yych == '=') goto yy292;
			}
			{ return TOK_DIVOP; }
yy12:
			++end;
			if((yych = (Char)*end) == '_') goto yy284;
			goto yy29;
yy13:
			{ return TOK_IDENTIFIER; }
yy14:
			yych = (Char)*++end;
			if(yych == 'o') goto yy275;
			if(yych == 'r') goto yy276;
			goto yy29;
yy15:
			yych = (Char)*++end;
			if(yych == 'a') goto yy259;
			if(yych == 'o') goto yy260;
			goto yy29;
yy16:
			yych = (Char)*++end;
			if(yych == 'e') goto yy252;
			goto yy29;
yy17:
			yych = (Char)*++end;
			if(yych == 'l') goto yy242;
			if(yych == 'x') goto yy243;
			goto yy29;
yy18:
			yych = (Char)*++end;
			if(yych <= 'i') {
				if(yych == 'a') goto yy219;
				if(yych <= 'h') goto yy29;
				goto yy220;
			} else {
				if(yych <= 'o') {
					if(yych <= 'n') goto yy29;
					goto yy221;
				} else {
					if(yych == 'u') goto yy222;
					goto yy29;
				}
			}
yy19:
			yych = (Char)*++end;
			if(yych == 'f') goto yy207;
			if(yych == 'n') goto yy209;
			goto yy29;
yy20:
			yych = (Char)*++end;
			if(yych <= 'd') {
				if(yych == 'a') goto yy191;
				goto yy29;
			} else {
				if(yych <= 'e') goto yy192;
				if(yych == 'u') goto yy193;
				goto yy29;
			}
yy21:
			yych = (Char)*++end;
			if(yych == 'p') goto yy183;
			goto yy29;
yy22:
			yych = (Char)*++end;
			if(yych == 'e') goto yy177;
			goto yy29;
yy23:
			yych = (Char)*++end;
			if(yych == 't') goto yy165;
			if(yych == 'w') goto yy166;
			goto yy29;
yy24:
			yych = (Char)*++end;
			if(yych == 'h') goto yy151;
			if(yych == 'r') goto yy152;
			goto yy29;
yy25:
			yych = (Char)*++end;
			if(yych == 'n') goto yy146;
			goto yy29;
yy26:
			yych = (Char)*++end;
			if(yych == 'a') goto yy143;
			goto yy29;
yy27:
			yych = (Char)*++end;
			if(yych == 'h') goto yy138;
			goto yy29;
yy28:
			++end;
			yych = (Char)*end;
yy29:
			if(yych & ~0xFF) {
				goto yy13;
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			goto yy13;
yy30:
			yyaccept = 0;
			yych = (Char)*(qptr = ++end);
			if(yych <= 'q') {
				if(yych == 'b') goto yy127;
				goto yy33;
			} else {
				if(yych <= 'r') goto yy126;
				if(yych == 'x') goto yy128;
				goto yy33;
			}
yy31:
			{ return TOK_LIT_INTEGER; }
yy32:
			yyaccept = 0;
			qptr = ++end;
			yych = (Char)*end;
yy33:
			if(yych & ~0xFF) {
				goto yy31;
			} else if(yybm[0+yych] & 8) {
				goto yy32;
			}
			if(yych == '.') goto yy122;
			goto yy31;
yy34:
			++end;
			{ return TOK_LIT_STRING; }
yy36:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
				goto yy118;
			} else if(yybm[0+yych] & 16) {
				goto yy118;
			}
			goto yy2;
yy37:
			yyaccept = 1;
			yych = (Char)*(qptr = ++end);
			if(yych == '.') goto yy115;
yy38:
			{ return TOK_DOT; }
yy39:
			++end;
			if((yych = (Char)*end) == '=') goto yy111;
			{ return TOK_ASSIGN; }
yy41:
			++end;
			if((yych = (Char)*end) == '=') goto yy107;
			{ return TOK_NOT; }
yy43:
			++end;
			if((yych = (Char)*end) == '=') goto yy105;
			if(yych == '?') goto yy103;
			{ return TOK_LT; }
yy45:
			++end;
			if((yych = (Char)*end) == '=') goto yy101;
			{ return TOK_GT; }
yy47:
			++end;
			if((yych = (Char)*end) == '+') goto yy99;
			if(yych == '=') goto yy97;
			{ return TOK_ADDOP; }
yy49:
			++end;
			if((yych = (Char)*end) == '-') goto yy95;
			if(yych == '=') goto yy93;
			{ return TOK_SUBOP; }
yy51:
			++end;
			if((yych = (Char)*end) == '=') goto yy91;
			{ return TOK_MULOP; }
yy53:
			++end;
			if((yych = (Char)*end) == '=') goto yy89;
			{ return TOK_MODOP; }
yy55:
			++end;
			if((yych = (Char)*end) == '|') goto yy87;
			{ return TOK_BITOR; }
yy57:
			++end;
			if((yych = (Char)*end) == '&') goto yy85;
			{ return TOK_BITAND; }
yy59:
			++end;
			if((yych = (Char)*end) == '>') goto yy83;
			{ return TOK_QUESTION; }
yy61:
			++end;
			if((yych = (Char)*end) == ':') goto yy81;
			{ return TOK_COLON; }
yy63:
			++end;
			{ return TOK_SEMICOLON; }
yy65:
			++end;
			{ return TOK_COMMA; }
yy67:
			++end;
			{ return TOK_BITXOR; }
yy69:
			++end;
			{ return TOK_LBRACKET; }
yy71:
			++end;
			{ return TOK_RBRACKET; }
yy73:
			++end;
			{ return TOK_LPAREN; }
yy75:
			++end;
			{ return TOK_RPAREN; }
yy77:
			++end;
			{ return TOK_LBRACE; }
yy79:
			++end;
			{ return TOK_RBRACE; }
yy81:
			++end;
			{ return TOK_NS_SEP; }
yy83:
			++end;
			{ return TOK_XMLPRC; }
yy85:
			++end;
			{ return TOK_LOGAND; }
yy87:
			++end;
			{ return TOK_LOGOR; }
yy89:
			++end;
			{ return TOK_ASSMOD; }
yy91:
			++end;
			{ return TOK_ASSMUL; }
yy93:
			++end;
			{ return TOK_ASSSUB; }
yy95:
			++end;
			{ return TOK_SUBSUB; }
yy97:
			++end;
			{ return TOK_ASSADD; }
yy99:
			++end;
			{ return TOK_ADDADD; }
yy101:
			++end;
			{ return TOK_GE; }
yy103:
			++end;
			{ return TOK_XMLPRO; }
yy105:
			++end;
			{ return TOK_LE; }
yy107:
			++end;
			if((yych = (Char)*end) == '=') goto yy109;
			{ return TOK_NEQUALS; }
yy109:
			++end;
			{ return TOK_SNE; }
yy111:
			++end;
			if((yych = (Char)*end) == '=') goto yy113;
			{ return TOK_EQUALS; }
yy113:
			++end;
			{ return TOK_SEQ; }
yy115:
			yych = (Char)*++end;
			if(yych != '.') goto yy2;
			++end;
			{ return TOK_VARIADIC; }
yy118:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 16) {
				goto yy118;
			}
			++end;
			{ return TOK_SHELLCMD; }
yy122:
			yych = (Char)*++end;
			if(yych <= '/') goto yy2;
			if(yych >= ':') goto yy2;
yy123:
			++end;
			yych = (Char)*end;
			if(yych <= '/') goto yy125;
			if(yych <= '9') goto yy123;
yy125:
			{ return TOK_LIT_REAL; }
yy126:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
				goto yy2;
			} else if(yybm[0+yych] & 128) {
				goto yy135;
			}
			goto yy2;
yy127:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
				goto yy2;
			} else if(yybm[0+yych] & 64) {
				goto yy132;
			}
			goto yy2;
yy128:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 32) {
				goto yy129;
			}
			goto yy2;
yy129:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 32) {
				goto yy129;
			}
			{ return TOK_LIT_HEX; }
yy132:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 64) {
				goto yy132;
			}
			{ return TOK_LIT_BIN; }
yy135:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 128) {
				goto yy135;
			}
			{ return TOK_LIT_ROM; }
yy138:
			yych = (Char)*++end;
			if(yych != 'i') goto yy29;
			yych = (Char)*++end;
			if(yych != 'l') goto yy29;
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_WHILE; }
yy143:
			yych = (Char)*++end;
			if(yych != 'r') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_VAR; }
yy146:
			yych = (Char)*++end;
			if(yych != 's') goto yy29;
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			yych = (Char)*++end;
			if(yych != 't') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_UNSET; }
yy151:
			yych = (Char)*++end;
			if(yych == 'i') goto yy158;
			if(yych == 'r') goto yy159;
			goto yy29;
yy152:
			yych = (Char)*++end;
			if(yych == 'u') goto yy153;
			if(yych == 'y') goto yy154;
			goto yy29;
yy153:
			yych = (Char)*++end;
			if(yych == 'e') goto yy156;
			goto yy29;
yy154:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_TRY; }
yy156:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_TRUE; }
yy158:
			yych = (Char)*++end;
			if(yych == 's') goto yy163;
			goto yy29;
yy159:
			yych = (Char)*++end;
			if(yych != 'o') goto yy29;
			yych = (Char)*++end;
			if(yych != 'w') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_THROW; }
yy163:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_THIS; }
yy165:
			yych = (Char)*++end;
			if(yych == 'r') goto yy172;
			goto yy29;
yy166:
			yych = (Char)*++end;
			if(yych != 'i') goto yy29;
			yych = (Char)*++end;
			if(yych != 't') goto yy29;
			yych = (Char)*++end;
			if(yych != 'c') goto yy29;
			yych = (Char)*++end;
			if(yych != 'h') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_SWITCH; }
yy172:
			yych = (Char)*++end;
			if(yych != 'i') goto yy29;
			yych = (Char)*++end;
			if(yych != 'n') goto yy29;
			yych = (Char)*++end;
			if(yych != 'g') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_STRING; }
yy177:
			yych = (Char)*++end;
			if(yych != 't') goto yy29;
			yych = (Char)*++end;
			if(yych != 'u') goto yy29;
			yych = (Char)*++end;
			if(yych != 'r') goto yy29;
			yych = (Char)*++end;
			if(yych != 'n') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_RETURN; }
yy183:
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			yych = (Char)*++end;
			if(yych != 'r') goto yy29;
			yych = (Char)*++end;
			if(yych != 'a') goto yy29;
			yych = (Char)*++end;
			if(yych != 't') goto yy29;
			yych = (Char)*++end;
			if(yych != 'o') goto yy29;
			yych = (Char)*++end;
			if(yych != 'r') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_OPERATOR; }
yy191:
			yych = (Char)*++end;
			if(yych == 'm') goto yy199;
			goto yy29;
yy192:
			yych = (Char)*++end;
			if(yych == 'w') goto yy197;
			goto yy29;
yy193:
			yych = (Char)*++end;
			if(yych != 'l') goto yy29;
			yych = (Char)*++end;
			if(yych != 'l') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_NULL; }
yy197:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_NEW; }
yy199:
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			yych = (Char)*++end;
			if(yych != 's') goto yy29;
			yych = (Char)*++end;
			if(yych != 'p') goto yy29;
			yych = (Char)*++end;
			if(yych != 'a') goto yy29;
			yych = (Char)*++end;
			if(yych != 'c') goto yy29;
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_NAMESPACE; }
yy207:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_IF; }
yy209:
			++end;
			if((yych = (Char)*end) <= '_') {
				if(yych <= '@') {
					if(yych <= '/') goto yy210;
					if(yych <= '9') goto yy28;
				} else {
					if(yych <= 'Z') goto yy28;
					if(yych >= '_') goto yy28;
				}
			} else {
				if(yych <= 'c') {
					if(yych <= '`') goto yy210;
					if(yych <= 'b') goto yy28;
					goto yy211;
				} else {
					if(yych == 't') goto yy212;
					if(yych <= 'z') goto yy28;
				}
			}
yy210:
			{ return TOK_IN; }
yy211:
			yych = (Char)*++end;
			if(yych == 'l') goto yy214;
			goto yy29;
yy212:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_INT; }
yy214:
			yych = (Char)*++end;
			if(yych != 'u') goto yy29;
			yych = (Char)*++end;
			if(yych != 'd') goto yy29;
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_INCLUDE; }
yy219:
			yych = (Char)*++end;
			if(yych == 'l') goto yy238;
			goto yy29;
yy220:
			yych = (Char)*++end;
			if(yych == 'n') goto yy232;
			goto yy29;
yy221:
			yych = (Char)*++end;
			if(yych == 'r') goto yy230;
			goto yy29;
yy222:
			yych = (Char)*++end;
			if(yych != 'n') goto yy29;
			yych = (Char)*++end;
			if(yych != 'c') goto yy29;
			yych = (Char)*++end;
			if(yych != 't') goto yy29;
			yych = (Char)*++end;
			if(yych != 'i') goto yy29;
			yych = (Char)*++end;
			if(yych != 'o') goto yy29;
			yych = (Char)*++end;
			if(yych != 'n') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_FUNCTION; }
yy230:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_FOR; }
yy232:
			yych = (Char)*++end;
			if(yych != 'a') goto yy29;
			yych = (Char)*++end;
			if(yych != 'l') goto yy29;
			yych = (Char)*++end;
			if(yych != 'l') goto yy29;
			yych = (Char)*++end;
			if(yych != 'y') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_FINALLY; }
yy238:
			yych = (Char)*++end;
			if(yych != 's') goto yy29;
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_FALSE; }
yy242:
			yych = (Char)*++end;
			if(yych == 's') goto yy249;
			goto yy29;
yy243:
			yych = (Char)*++end;
			if(yych != 't') goto yy29;
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			yych = (Char)*++end;
			if(yych != 'r') goto yy29;
			yych = (Char)*++end;
			if(yych != 'n') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_EXTERN; }
yy249:
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_ELSE; }
yy252:
			yych = (Char)*++end;
			if(yych != 'f') goto yy29;
			yych = (Char)*++end;
			if(yych != 'a') goto yy29;
			yych = (Char)*++end;
			if(yych != 'u') goto yy29;
			yych = (Char)*++end;
			if(yych != 'l') goto yy29;
			yych = (Char)*++end;
			if(yych != 't') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_DEFAULT; }
yy259:
			yych = (Char)*++end;
			if(yych <= 'r') goto yy29;
			if(yych <= 's') goto yy268;
			if(yych <= 't') goto yy269;
			goto yy29;
yy260:
			yych = (Char)*++end;
			if(yych != 'n') goto yy29;
			yych = (Char)*++end;
			if(yych != 't') goto yy29;
			yych = (Char)*++end;
			if(yych != 'i') goto yy29;
			yych = (Char)*++end;
			if(yych != 'n') goto yy29;
			yych = (Char)*++end;
			if(yych != 'u') goto yy29;
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_CONTINUE; }
yy268:
			yych = (Char)*++end;
			if(yych == 'e') goto yy273;
			goto yy29;
yy269:
			yych = (Char)*++end;
			if(yych != 'c') goto yy29;
			yych = (Char)*++end;
			if(yych != 'h') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_CATCH; }
yy273:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_CASE; }
yy275:
			yych = (Char)*++end;
			if(yych == 'o') goto yy281;
			goto yy29;
yy276:
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			yych = (Char)*++end;
			if(yych != 'a') goto yy29;
			yych = (Char)*++end;
			if(yych != 'k') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_BREAK; }
yy281:
			yych = (Char)*++end;
			if(yych != 'l') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_BOOL; }
yy284:
			yych = (Char)*++end;
			if(yych != 'n') goto yy29;
			yych = (Char)*++end;
			if(yych != 'a') goto yy29;
			yych = (Char)*++end;
			if(yych != 't') goto yy29;
			yych = (Char)*++end;
			if(yych != 'i') goto yy29;
			yych = (Char)*++end;
			if(yych != 'v') goto yy29;
			yych = (Char)*++end;
			if(yych != 'e') goto yy29;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy28;
			}
			{ return TOK_NATIVE; }
yy292:
			++end;
			{ return TOK_ASSDIV; }
yy294:
			++end;
			{ return TOK_COMMENT; }
yy296:
			++end;
			{ return TOK_COMMENT; }
		}
	}

}
