/* Generated by re2c 0.12.2 */
//////////////////////////////////////////////////////////////////////////
//
// This file is © 2007 - 2009 JJ Fahner <jan-jaap@jan-jaap.net>
// This file is part of the cscript interpreter.
// CScript can be found at http://svn.jan-jaap.net/
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//////////////////////////////////////////////////////////////////////////

int parseNextToken(Char*& start, Char*& end)
{
  Char* qptr = 0;
  
  if(*start == 0)
  {
    return 0;
  }
  
  	{
		static const unsigned char yybm[] = {
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  17,  16,  16,  16,  18,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 17,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			124, 124,  60,  60,  60,  60,  60,  60, 
			 60,  60,  16,  16,  16,  16,  16,  16, 
			 16,  52,  52, 180, 180,  52,  52,  20, 
			 20, 148,  20,  20, 148, 148,  20, 148, 
			 20,  20,  20,  20,  20,  20, 148,  20, 
			148,  20,  20,  16,  16,  16,  16,  20, 
			  0,  52,  52,  52,  52,  52,  52,  20, 
			 20,  20,  20,  20,  20,  20,  20,  20, 
			 20,  20,  20,  20,  20,  20,  20,  20, 
			 20,  20,  20,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
			 16,  16,  16,  16,  16,  16,  16,  16, 
		};

		{
			Char yych;
			unsigned int yyaccept = 0;

			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 1) {
				goto yy3;
			}
			switch(yych) {
			case 0x000A:	goto yy8;
			case 0x000D:	goto yy6;
			case '!':	goto yy39;
			case '"':	goto yy32;
			case '%':	goto yy51;
			case '&':	goto yy55;
			case '(':	goto yy71;
			case ')':	goto yy73;
			case '*':	goto yy49;
			case '+':	goto yy45;
			case ',':	goto yy63;
			case '-':	goto yy47;
			case '.':	goto yy35;
			case '/':	goto yy10;
			case '0':	goto yy28;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy30;
			case ':':	goto yy59;
			case ';':	goto yy61;
			case '<':	goto yy41;
			case '=':	goto yy37;
			case '>':	goto yy43;
			case '?':	goto yy57;
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'g':
			case 'h':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'o':
			case 'p':
			case 'q':
			case 'u':
			case 'x':
			case 'y':
			case 'z':	goto yy26;
			case '[':	goto yy67;
			case ']':	goto yy69;
			case '^':	goto yy65;
			case '_':	goto yy12;
			case '`':	goto yy34;
			case 'b':	goto yy14;
			case 'c':	goto yy15;
			case 'd':	goto yy16;
			case 'e':	goto yy17;
			case 'f':	goto yy18;
			case 'i':	goto yy19;
			case 'n':	goto yy20;
			case 'r':	goto yy21;
			case 's':	goto yy22;
			case 't':	goto yy23;
			case 'v':	goto yy24;
			case 'w':	goto yy25;
			case '{':	goto yy75;
			case '|':	goto yy53;
			case '}':	goto yy77;
			default:	goto yy2;
			}
yy2:
			end = qptr;
			if(yyaccept <= 0) {
				goto yy29;
			} else {
				goto yy36;
			}
yy3:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 1) {
				goto yy3;
			}
			{ return TOK_WHITESPACE; }
yy6:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
				goto yy2;
			} else if(yybm[0+yych] & 2) {
				goto yy6;
			}
			if(yych != 0x000A) goto yy2;
yy8:
			++end;
			{ return TOK_NEWLINE; }
yy10:
			++end;
			if((yych = (Char)*end) <= '.') {
				if(yych == '*') goto yy279;
			} else {
				if(yych <= '/') goto yy281;
				if(yych == '=') goto yy277;
			}
			{ return TOK_DIVOP; }
yy12:
			++end;
			if((yych = (Char)*end) == '_') goto yy269;
			goto yy27;
yy13:
			{ return TOK_IDENTIFIER; }
yy14:
			yych = (Char)*++end;
			if(yych == 'o') goto yy260;
			if(yych == 'r') goto yy261;
			goto yy27;
yy15:
			yych = (Char)*++end;
			if(yych == 'a') goto yy244;
			if(yych == 'o') goto yy245;
			goto yy27;
yy16:
			yych = (Char)*++end;
			if(yych == 'e') goto yy237;
			goto yy27;
yy17:
			yych = (Char)*++end;
			if(yych == 'l') goto yy227;
			if(yych == 'x') goto yy228;
			goto yy27;
yy18:
			yych = (Char)*++end;
			if(yych <= 'i') {
				if(yych == 'a') goto yy204;
				if(yych <= 'h') goto yy27;
				goto yy205;
			} else {
				if(yych <= 'o') {
					if(yych <= 'n') goto yy27;
					goto yy206;
				} else {
					if(yych == 'u') goto yy207;
					goto yy27;
				}
			}
yy19:
			yych = (Char)*++end;
			if(yych == 'f') goto yy192;
			if(yych == 'n') goto yy194;
			goto yy27;
yy20:
			yych = (Char)*++end;
			if(yych <= 'd') {
				if(yych == 'a') goto yy176;
				goto yy27;
			} else {
				if(yych <= 'e') goto yy177;
				if(yych == 'u') goto yy178;
				goto yy27;
			}
yy21:
			yych = (Char)*++end;
			if(yych == 'e') goto yy170;
			goto yy27;
yy22:
			yych = (Char)*++end;
			if(yych == 't') goto yy158;
			if(yych == 'w') goto yy159;
			goto yy27;
yy23:
			yych = (Char)*++end;
			if(yych == 'h') goto yy144;
			if(yych == 'r') goto yy145;
			goto yy27;
yy24:
			yych = (Char)*++end;
			if(yych == 'a') goto yy141;
			goto yy27;
yy25:
			yych = (Char)*++end;
			if(yych == 'h') goto yy136;
			goto yy27;
yy26:
			++end;
			yych = (Char)*end;
yy27:
			if(yych & ~0xFF) {
				goto yy13;
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			goto yy13;
yy28:
			yyaccept = 0;
			yych = (Char)*(qptr = ++end);
			if(yych <= 'q') {
				if(yych == 'b') goto yy125;
				goto yy31;
			} else {
				if(yych <= 'r') goto yy124;
				if(yych == 'x') goto yy126;
				goto yy31;
			}
yy29:
			{ return TOK_LIT_INTEGER; }
yy30:
			yyaccept = 0;
			qptr = ++end;
			yych = (Char)*end;
yy31:
			if(yych & ~0xFF) {
				goto yy29;
			} else if(yybm[0+yych] & 8) {
				goto yy30;
			}
			if(yych == '.') goto yy120;
			goto yy29;
yy32:
			++end;
			{ return TOK_LIT_STRING; }
yy34:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
				goto yy116;
			} else if(yybm[0+yych] & 16) {
				goto yy116;
			}
			goto yy2;
yy35:
			yyaccept = 1;
			yych = (Char)*(qptr = ++end);
			if(yych == '.') goto yy113;
yy36:
			{ return TOK_DOT; }
yy37:
			++end;
			if((yych = (Char)*end) == '=') goto yy109;
			{ return TOK_ASSIGN; }
yy39:
			++end;
			if((yych = (Char)*end) == '=') goto yy105;
			{ return TOK_NOT; }
yy41:
			++end;
			if((yych = (Char)*end) == '=') goto yy103;
			if(yych == '?') goto yy101;
			{ return TOK_ST; }
yy43:
			++end;
			if((yych = (Char)*end) == '=') goto yy99;
			{ return TOK_GT; }
yy45:
			++end;
			if((yych = (Char)*end) == '+') goto yy97;
			if(yych == '=') goto yy95;
			{ return TOK_ADDOP; }
yy47:
			++end;
			if((yych = (Char)*end) == '-') goto yy93;
			if(yych == '=') goto yy91;
			{ return TOK_SUBOP; }
yy49:
			++end;
			if((yych = (Char)*end) == '=') goto yy89;
			{ return TOK_MULOP; }
yy51:
			++end;
			if((yych = (Char)*end) == '=') goto yy87;
			{ return TOK_MODOP; }
yy53:
			++end;
			if((yych = (Char)*end) == '|') goto yy85;
			{ return TOK_BITOR; }
yy55:
			++end;
			if((yych = (Char)*end) == '&') goto yy83;
			{ return TOK_BITAND; }
yy57:
			++end;
			if((yych = (Char)*end) == '>') goto yy81;
			{ return TOK_QUESTION; }
yy59:
			++end;
			if((yych = (Char)*end) == ':') goto yy79;
			{ return TOK_COLON; }
yy61:
			++end;
			{ return TOK_SEMICOLON; }
yy63:
			++end;
			{ return TOK_COMMA; }
yy65:
			++end;
			{ return TOK_BITXOR; }
yy67:
			++end;
			{ return TOK_LBRACKET; }
yy69:
			++end;
			{ return TOK_RBRACKET; }
yy71:
			++end;
			{ return TOK_LPAREN; }
yy73:
			++end;
			{ return TOK_RPAREN; }
yy75:
			++end;
			{ return TOK_LBRACE; }
yy77:
			++end;
			{ return TOK_RBRACE; }
yy79:
			++end;
			{ return TOK_NS_SEP; }
yy81:
			++end;
			{ return TOK_XMLPRC; }
yy83:
			++end;
			{ return TOK_LOGAND; }
yy85:
			++end;
			{ return TOK_LOGOR; }
yy87:
			++end;
			{ return TOK_ASSMOD; }
yy89:
			++end;
			{ return TOK_ASSMUL; }
yy91:
			++end;
			{ return TOK_ASSSUB; }
yy93:
			++end;
			{ return TOK_SUBSUB; }
yy95:
			++end;
			{ return TOK_ASSADD; }
yy97:
			++end;
			{ return TOK_ADDADD; }
yy99:
			++end;
			{ return TOK_GE; }
yy101:
			++end;
			{ return TOK_XMLPRO; }
yy103:
			++end;
			{ return TOK_SE; }
yy105:
			++end;
			if((yych = (Char)*end) == '=') goto yy107;
			{ return TOK_NEQUALS; }
yy107:
			++end;
			{ return TOK_SNE; }
yy109:
			++end;
			if((yych = (Char)*end) == '=') goto yy111;
			{ return TOK_EQUALS; }
yy111:
			++end;
			{ return TOK_SEQ; }
yy113:
			yych = (Char)*++end;
			if(yych != '.') goto yy2;
			++end;
			{ return TOK_VARIADIC; }
yy116:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 16) {
				goto yy116;
			}
			++end;
			{ return TOK_SHELLCMD; }
yy120:
			yych = (Char)*++end;
			if(yych <= '/') goto yy2;
			if(yych >= ':') goto yy2;
yy121:
			++end;
			yych = (Char)*end;
			if(yych <= '/') goto yy123;
			if(yych <= '9') goto yy121;
yy123:
			{ return TOK_LIT_REAL; }
yy124:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
				goto yy2;
			} else if(yybm[0+yych] & 128) {
				goto yy133;
			}
			goto yy2;
yy125:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
				goto yy2;
			} else if(yybm[0+yych] & 64) {
				goto yy130;
			}
			goto yy2;
yy126:
			yych = (Char)*++end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 32) {
				goto yy127;
			}
			goto yy2;
yy127:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 32) {
				goto yy127;
			}
			{ return TOK_LIT_HEX; }
yy130:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 64) {
				goto yy130;
			}
			{ return TOK_LIT_BIN; }
yy133:
			++end;
			yych = (Char)*end;
			if(yych & ~0xFF) {
			} else if(yybm[0+yych] & 128) {
				goto yy133;
			}
			{ return TOK_LIT_ROM; }
yy136:
			yych = (Char)*++end;
			if(yych != 'i') goto yy27;
			yych = (Char)*++end;
			if(yych != 'l') goto yy27;
			yych = (Char)*++end;
			if(yych != 'e') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_WHILE; }
yy141:
			yych = (Char)*++end;
			if(yych != 'r') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_VAR; }
yy144:
			yych = (Char)*++end;
			if(yych == 'i') goto yy151;
			if(yych == 'r') goto yy152;
			goto yy27;
yy145:
			yych = (Char)*++end;
			if(yych == 'u') goto yy146;
			if(yych == 'y') goto yy147;
			goto yy27;
yy146:
			yych = (Char)*++end;
			if(yych == 'e') goto yy149;
			goto yy27;
yy147:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_TRY; }
yy149:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_TRUE; }
yy151:
			yych = (Char)*++end;
			if(yych == 's') goto yy156;
			goto yy27;
yy152:
			yych = (Char)*++end;
			if(yych != 'o') goto yy27;
			yych = (Char)*++end;
			if(yych != 'w') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_THROW; }
yy156:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_THIS; }
yy158:
			yych = (Char)*++end;
			if(yych == 'r') goto yy165;
			goto yy27;
yy159:
			yych = (Char)*++end;
			if(yych != 'i') goto yy27;
			yych = (Char)*++end;
			if(yych != 't') goto yy27;
			yych = (Char)*++end;
			if(yych != 'c') goto yy27;
			yych = (Char)*++end;
			if(yych != 'h') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_SWITCH; }
yy165:
			yych = (Char)*++end;
			if(yych != 'i') goto yy27;
			yych = (Char)*++end;
			if(yych != 'n') goto yy27;
			yych = (Char)*++end;
			if(yych != 'g') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_STRING; }
yy170:
			yych = (Char)*++end;
			if(yych != 't') goto yy27;
			yych = (Char)*++end;
			if(yych != 'u') goto yy27;
			yych = (Char)*++end;
			if(yych != 'r') goto yy27;
			yych = (Char)*++end;
			if(yych != 'n') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_RETURN; }
yy176:
			yych = (Char)*++end;
			if(yych == 'm') goto yy184;
			goto yy27;
yy177:
			yych = (Char)*++end;
			if(yych == 'w') goto yy182;
			goto yy27;
yy178:
			yych = (Char)*++end;
			if(yych != 'l') goto yy27;
			yych = (Char)*++end;
			if(yych != 'l') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_NULL; }
yy182:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_NEW; }
yy184:
			yych = (Char)*++end;
			if(yych != 'e') goto yy27;
			yych = (Char)*++end;
			if(yych != 's') goto yy27;
			yych = (Char)*++end;
			if(yych != 'p') goto yy27;
			yych = (Char)*++end;
			if(yych != 'a') goto yy27;
			yych = (Char)*++end;
			if(yych != 'c') goto yy27;
			yych = (Char)*++end;
			if(yych != 'e') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_NAMESPACE; }
yy192:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_IF; }
yy194:
			++end;
			if((yych = (Char)*end) <= '_') {
				if(yych <= '@') {
					if(yych <= '/') goto yy195;
					if(yych <= '9') goto yy26;
				} else {
					if(yych <= 'Z') goto yy26;
					if(yych >= '_') goto yy26;
				}
			} else {
				if(yych <= 'c') {
					if(yych <= '`') goto yy195;
					if(yych <= 'b') goto yy26;
					goto yy196;
				} else {
					if(yych == 't') goto yy197;
					if(yych <= 'z') goto yy26;
				}
			}
yy195:
			{ return TOK_IN; }
yy196:
			yych = (Char)*++end;
			if(yych == 'l') goto yy199;
			goto yy27;
yy197:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_INT; }
yy199:
			yych = (Char)*++end;
			if(yych != 'u') goto yy27;
			yych = (Char)*++end;
			if(yych != 'd') goto yy27;
			yych = (Char)*++end;
			if(yych != 'e') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_INCLUDE; }
yy204:
			yych = (Char)*++end;
			if(yych == 'l') goto yy223;
			goto yy27;
yy205:
			yych = (Char)*++end;
			if(yych == 'n') goto yy217;
			goto yy27;
yy206:
			yych = (Char)*++end;
			if(yych == 'r') goto yy215;
			goto yy27;
yy207:
			yych = (Char)*++end;
			if(yych != 'n') goto yy27;
			yych = (Char)*++end;
			if(yych != 'c') goto yy27;
			yych = (Char)*++end;
			if(yych != 't') goto yy27;
			yych = (Char)*++end;
			if(yych != 'i') goto yy27;
			yych = (Char)*++end;
			if(yych != 'o') goto yy27;
			yych = (Char)*++end;
			if(yych != 'n') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_FUNCTION; }
yy215:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_FOR; }
yy217:
			yych = (Char)*++end;
			if(yych != 'a') goto yy27;
			yych = (Char)*++end;
			if(yych != 'l') goto yy27;
			yych = (Char)*++end;
			if(yych != 'l') goto yy27;
			yych = (Char)*++end;
			if(yych != 'y') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_FINALLY; }
yy223:
			yych = (Char)*++end;
			if(yych != 's') goto yy27;
			yych = (Char)*++end;
			if(yych != 'e') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_FALSE; }
yy227:
			yych = (Char)*++end;
			if(yych == 's') goto yy234;
			goto yy27;
yy228:
			yych = (Char)*++end;
			if(yych != 't') goto yy27;
			yych = (Char)*++end;
			if(yych != 'e') goto yy27;
			yych = (Char)*++end;
			if(yych != 'r') goto yy27;
			yych = (Char)*++end;
			if(yych != 'n') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_EXTERN; }
yy234:
			yych = (Char)*++end;
			if(yych != 'e') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_ELSE; }
yy237:
			yych = (Char)*++end;
			if(yych != 'f') goto yy27;
			yych = (Char)*++end;
			if(yych != 'a') goto yy27;
			yych = (Char)*++end;
			if(yych != 'u') goto yy27;
			yych = (Char)*++end;
			if(yych != 'l') goto yy27;
			yych = (Char)*++end;
			if(yych != 't') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_DEFAULT; }
yy244:
			yych = (Char)*++end;
			if(yych <= 'r') goto yy27;
			if(yych <= 's') goto yy253;
			if(yych <= 't') goto yy254;
			goto yy27;
yy245:
			yych = (Char)*++end;
			if(yych != 'n') goto yy27;
			yych = (Char)*++end;
			if(yych != 't') goto yy27;
			yych = (Char)*++end;
			if(yych != 'i') goto yy27;
			yych = (Char)*++end;
			if(yych != 'n') goto yy27;
			yych = (Char)*++end;
			if(yych != 'u') goto yy27;
			yych = (Char)*++end;
			if(yych != 'e') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_CONTINUE; }
yy253:
			yych = (Char)*++end;
			if(yych == 'e') goto yy258;
			goto yy27;
yy254:
			yych = (Char)*++end;
			if(yych != 'c') goto yy27;
			yych = (Char)*++end;
			if(yych != 'h') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_CATCH; }
yy258:
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_CASE; }
yy260:
			yych = (Char)*++end;
			if(yych == 'o') goto yy266;
			goto yy27;
yy261:
			yych = (Char)*++end;
			if(yych != 'e') goto yy27;
			yych = (Char)*++end;
			if(yych != 'a') goto yy27;
			yych = (Char)*++end;
			if(yych != 'k') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_BREAK; }
yy266:
			yych = (Char)*++end;
			if(yych != 'l') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_BOOL; }
yy269:
			yych = (Char)*++end;
			if(yych != 'n') goto yy27;
			yych = (Char)*++end;
			if(yych != 'a') goto yy27;
			yych = (Char)*++end;
			if(yych != 't') goto yy27;
			yych = (Char)*++end;
			if(yych != 'i') goto yy27;
			yych = (Char)*++end;
			if(yych != 'v') goto yy27;
			yych = (Char)*++end;
			if(yych != 'e') goto yy27;
			++end;
			if((yych = (Char)*end) & ~0xFF) {
			} else if(yybm[0+yych] & 4) {
				goto yy26;
			}
			{ return TOK_NATIVE; }
yy277:
			++end;
			{ return TOK_ASSDIV; }
yy279:
			++end;
			{ return TOK_COMMENT; }
yy281:
			++end;
			{ return TOK_COMMENT; }
		}
	}

}
